/**
 * BENGKEL MALAM
 * Race Game Logic
 *
 * RESPONSIBILITY:
 * - Validate race entry.
 * - Validate motor + driver compatibility.
 * - Calculate race performance.
 * - Simulate launch / acceleration / top speed / handling /
 *   braking / consistency / reliability.
 * - Produce finish order.
 * - Produce finish time.
 * - Calculate rewards.
 * - Calculate motor / part wear.
 * - Calculate championship points.
 *
 * IMPORTANT:
 * - Tidak menggunakan localStorage.
 * - Tidak menyimpan hasil race.
 * - Tidak mengubah GameState secara langsung.
 * - Semua hasil dikembalikan sebagai object baru.
 *
 * MASTER DATA:
 * - ../data/races.ts
 * - ../data/motors.ts
 * - ../data/drivers.ts
 *
 * INSTANCE DATA:
 * - ./motor.ts
 */

/* -------------------------------------------------------------------------- */
/* IMPORTS                                                                    */
/* -------------------------------------------------------------------------- */

import {
  getRaceById,
  type RaceDefinition,
  type RaceClass,
} from "../data/races";

import {
  getDriverById,
  type DriverDefinition,
  type DriverClass,
} from "../data/drivers";

import {
  getMotorDefinition,
  calculateMotorStats,
  getMotorBuildScore,
  getMotorRaceReadiness,
  type MotorInstance,
} from "./motor";

/* -------------------------------------------------------------------------- */
/* TYPES                                                                      */
/* -------------------------------------------------------------------------- */

export interface RacePlayerContext {
  garageLevel: number;
  reputation: number;

  /**
   * Optional license IDs held by the player.
   *
   * Examples:
   * ["D"]
   * ["D", "C"]
   */
  licenses?: string[];

  /**
   * Optional team level.
   */
  teamLevel?: number;

  /**
   * Optional completed championship IDs.
   */
  championships?: string[];
}

export interface RaceEntry {
  /**
   * Static race ID.
   */
  raceId: string;

  /**
   * Player-owned motor instance.
   */
  motor: MotorInstance;

  /**
   * Static driver ID.
   */
  driverId: string;

  /**
   * Optional player setup modifiers.
   *
   * Intended for future setup screen.
   */
  setupModifiers?: RaceSetupModifiers;
}

export interface RaceSetupModifiers {
  launch?: number;
  acceleration?: number;
  topSpeed?: number;
  braking?: number;
  handling?: number;
  consistency?: number;
  reliability?: number;
}

export type RaceEntryErrorCode =
  | "RACE_NOT_FOUND"
  | "DRIVER_NOT_FOUND"
  | "MOTOR_NOT_FOUND"
  | "RACE_LOCKED"
  | "WRONG_MOTOR_CLASS"
  | "DRIVER_CLASS_NOT_ELIGIBLE"
  | "MOTOR_NOT_READY"
  | "MOTOR_CONDITION_TOO_LOW"
  | "LICENSE_REQUIRED"
  | "REPUTATION_TOO_LOW"
  | "GARAGE_LEVEL_TOO_LOW"
  | "TEAM_LEVEL_TOO_LOW"
  | "CHAMPIONSHIP_REQUIREMENT"
  | "MISSING_DRIVER_LEVEL"
  | "INVALID_ENTRY";

export interface RaceEntryValidation {
  valid: boolean;
  errors: RaceEntryErrorCode[];
  messages: string[];
  warnings: string[];
}

export interface RacePerformance {
  launch: number;
  acceleration: number;
  topSpeed: number;
  braking: number;
  handling: number;

  reaction: number;
  consistency: number;
  reliability: number;

  overall: number;

  /**
   * Useful for race debugging / UI.
   */
  weightedScore: number;

  /**
   * Random performance swing applied by race simulation.
   */
  variance: number;

  /**
   * Mechanical / reliability penalty applied.
   */
  reliabilityPenalty: number;
}

export interface RaceSimulationDriver {
  id: string;
  name: string;

  motorClass: RaceClass;
  driverClass: DriverClass;

  motor?: MotorInstance;

  basePerformance: RacePerformance;

  finalPerformance: RacePerformance;

  finishTimeMs: number;

  position: number;

  dnf: boolean;

  dnfReason?: RaceDnfReason;
}

export type RaceDnfReason =
  | "ENGINE_FAILURE"
  | "MECHANICAL_FAILURE"
  | "CRASH"
  | "NO_FINISH";

export interface RaceResultReward {
  type:
    | "CASH"
    | "XP"
    | "REPUTATION"
    | "CHAMPIONSHIP_POINTS";

  amount: number;
}

export interface RaceResult {
  raceId: string;

  /**
   * Timestamp of simulation.
   */
  simulatedAt: number;

  /**
   * Player position.
   * 1 = winner.
   */
  playerPosition: number;

  /**
   * Whether player finished.
   */
  playerFinished: boolean;

  /**
   * Player finish time in milliseconds.
   */
  playerFinishTimeMs: number;

  /**
   * Formatted display value.
   */
  playerFinishTime: string;

  /**
   * Starting field size.
   */
  fieldSize: number;

  /**
   * Complete simulated field.
   */
  standings: RaceSimulationDriver[];

  /**
   * Direct + position rewards.
   */
  rewards: RaceResultReward[];

  /**
   * Motor wear generated by this race.
   */
  motorWear: number;

  /**
   * Part wear generated by this race.
   */
  partWear: Record<string, number>;

  /**
   * Championship points earned.
   */
  championshipPoints: number;

  /**
   * Race score shown to UI.
   */
  performanceScore: number;

  /**
   * Risk / mechanical information.
   */
  mechanicalRisk: number;

  /**
   * Random seed if supplied by caller.
   */
  seed?: number;
}

export interface RaceSimulationOptions {
  /**
   * Number of opponents.
   *
   * Default = race maximum - 1, capped by sensible value.
   */
  opponentCount?: number;

  /**
   * Optional opponent definitions.
   *
   * When omitted, race engine generates abstract opponents
   * from static driver/motor catalogs.
   */
  opponents?: RaceOpponentDefinition[];

  /**
   * Seeded RNG.
   *
   * A seed can be supplied for deterministic tests.
   */
  seed?: number;

  /**
   * Optional RNG injection.
   */
  random?: RandomFn;

  /**
   * Optional setup modifiers for player.
   */
  playerSetupModifiers?: RaceSetupModifiers;

  /**
   * Optional penalty / balancing factor.
   *
   * 1 = normal
   * <1 = easier
   * >1 = harder
   */
  difficultyMultiplier?: number;
}

export interface RaceOpponentDefinition {
  driverId: string;
  motorDefinitionId: string;

  /**
   * Optional simulated motor condition.
   */
  motorCondition?: number;

  /**
   * Optional simulated driver level.
   */
  driverLevel?: number;

  /**
   * Optional setup modifiers.
   */
  setupModifiers?: RaceSetupModifiers;
}

export type RandomFn = () => number;

/* -------------------------------------------------------------------------- */
/* CONSTANTS                                                                  */
/* -------------------------------------------------------------------------- */

const DEFAULT_OPPONENT_COUNT = 7;

const MIN_FINISH_TIME_MS = 8_000;

const MAX_FINISH_TIME_MS = 120_000;

const BASE_TIME_MS_BY_DISTANCE: Record<
  "SHORT" | "MEDIUM" | "LONG",
  number
> = {
  SHORT: 10_000,
  MEDIUM: 22_000,
  LONG: 38_000,
};

const PERFORMANCE_TIME_FACTOR = 0.72;

const MAX_VARIANCE_PERCENT = 0.06;

const DNF_BASE_CHANCE = 0.01;

const MOTOR_WEAR_BASE = 2.5;

const PART_WEAR_BASE = 2;

const HIGH_RISK_THRESHOLD = 60;

/* -------------------------------------------------------------------------- */
/* RNG                                                                        */
/* -------------------------------------------------------------------------- */

/**
 * Create a seeded pseudo-random generator.
 *
 * This is intentionally tiny and deterministic for testing.
 */
export function createSeededRandom(
  seed: number,
): RandomFn {
  let value =
    Math.floor(seed) >>> 0;

  return () => {
    value =
      (value * 1664525 +
        1013904223) >>>
      0;

    return (
      value /
      4_294_967_296
    );
  };
}

/**
 * Normalize random value.
 */
export function safeRandom(
  random: RandomFn,
): number {
  const value =
    random();

  if (
    !Number.isFinite(
      value,
    )
  ) {
    return 0.5;
  }

  return Math.min(
    0.999999,
    Math.max(0, value),
  );
}

/**
 * Pick random item.
 */
export function randomItem<T>(
  items: readonly T[],
  random: RandomFn,
): T | undefined {
  if (
    items.length === 0
  ) {
    return undefined;
  }

  const index =
    Math.floor(
      safeRandom(random) *
        items.length,
    );

  return items[index];
}

/* -------------------------------------------------------------------------- */
/* GENERAL HELPERS                                                            */
/* -------------------------------------------------------------------------- */

/**
 * Clamp a race stat to 0-100.
 */
export function clampRaceStat(
  value: number,
): number {
  if (
    !Number.isFinite(
      value,
    )
  ) {
    return 0;
  }

  return Math.round(
    Math.max(
      0,
      Math.min(
        100,
        value,
      ),
    ),
  );
}

/**
 * Clamp a number.
 */
export function clamp(
  value: number,
  min: number,
  max: number,
): number {
  return Math.min(
    max,
    Math.max(
      min,
      value,
    ),
  );
}

/**
 * Format race time.
 *
 * Example:
 * 10423 -> "10.423"
 */
export function formatRaceTime(
  milliseconds: number,
): string {
  const safe =
    Math.max(
      0,
      Math.round(
        milliseconds,
      ),
    );

  const seconds =
    Math.floor(
      safe / 1_000,
    );

  const millis =
    safe % 1_000;

  return `${seconds}.${millis
    .toString()
    .padStart(
      3,
      "0",
    )}`;
}

/**
 * Determine distance bucket.
 */
export function getRaceDistanceBucket(
  meters: number,
): "SHORT" | "MEDIUM" | "LONG" {
  if (
    meters <= 250
  ) {
    return "SHORT";
  }

  if (
    meters <= 600
  ) {
    return "MEDIUM";
  }

  return "LONG";
}

/**
 * Determine whether a requirement type is numeric.
 */
export function isNumericRaceRequirement(
  type: string,
): boolean {
  return (
    type ===
      "GARAGE_LEVEL" ||
    type ===
      "REPUTATION" ||
    type ===
      "DRIVER_LEVEL" ||
    type ===
      "TEAM_LEVEL" ||
    type ===
      "MOTOR_CONDITION"
  );
}

/* -------------------------------------------------------------------------- */
/* DRIVER HELPERS                                                             */
/* -------------------------------------------------------------------------- */

/**
 * Read driver display name safely.
 */
export function getRaceDriverName(
  driver:
    | DriverDefinition
    | undefined,
): string {
  if (!driver) {
    return "UNKNOWN DRIVER";
  }

  return (
    typeof driver.name ===
      "string" &&
    driver.name.trim()
      ? driver.name
      : driver.id
  );
}

/**
 * Read driver stat safely.
 *
 * Kept defensive so race engine remains compatible
 * with catalog versions that add/remove optional stats later.
 */
export function getDriverStat(
  driver:
    | DriverDefinition
    | undefined,
  key:
    | "reaction"
    | "launch"
    | "shifting"
    | "consistency"
    | "control"
    | "focus"
    | "aggression",
): number {
  if (!driver) {
    return 0;
  }

  const value =
    driver.stats?.[key];

  return clampRaceStat(
    typeof value ===
      "number"
      ? value
      : 0,
  );
}

/**
 * Calculate driver race-facing performance.
 */
export function getDriverRaceAttributes(
  driver:
    | DriverDefinition
    | undefined,
): {
  reaction: number;
  launch: number;
  consistency: number;
  control: number;
  focus: number;
  aggression: number;
} {
  return {
    reaction:
      getDriverStat(
        driver,
        "reaction",
      ),

    launch:
      getDriverStat(
        driver,
        "launch",
      ),

    consistency:
      getDriverStat(
        driver,
        "consistency",
      ),

    control:
      getDriverStat(
        driver,
        "control",
      ),

    focus:
      getDriverStat(
        driver,
        "focus",
      ),

    aggression:
      getDriverStat(
        driver,
        "aggression",
      ),
  };
}

/**
 * Optional driver-level scaling.
 *
 * Higher level gives a very small performance bump.
 */
export function getDriverLevelMultiplier(
  level = 1,
): number {
  const safeLevel =
    Math.max(
      1,
      Math.floor(
        level,
      ),
    );

  return (
    1 +
    Math.min(
      0.12,
      (safeLevel - 1) *
        0.02,
    )
  );
}

/* -------------------------------------------------------------------------- */
/* MOTOR HELPERS                                                              */
/* -------------------------------------------------------------------------- */

/**
 * Read motor race attributes.
 */
export function getMotorRaceAttributes(
  motor:
    | MotorInstance
    | undefined,
): {
  launch: number;
  acceleration: number;
  topSpeed: number;
  braking: number;
  handling: number;
  reliability: number;
} {
  if (!motor) {
    return {
      launch: 0,
      acceleration: 0,
      topSpeed: 0,
      braking: 0,
      handling: 0,
      reliability: 0,
    };
  }

  const stats =
    calculateMotorStats(
      motor,
    );

  return {
    launch:
      clampRaceStat(
        stats.launch,
      ),

    acceleration:
      clampRaceStat(
        stats.acceleration,
      ),

    topSpeed:
      clampRaceStat(
        stats.topSpeed,
      ),

    braking:
      clampRaceStat(
        stats.braking,
      ),

    handling:
      clampRaceStat(
        stats.handling,
      ),

    reliability:
      clampRaceStat(
        stats.reliability,
      ),
  };
}

/**
 * Return motor class.
 */
export function getMotorRaceClass(
  motor:
    | MotorInstance
    | undefined,
): RaceClass | undefined {
  return getMotorDefinition(
    motor,
  )?.class;
}

/* -------------------------------------------------------------------------- */
/* RACE REQUIREMENT VALIDATION                                                */
/* -------------------------------------------------------------------------- */

/**
 * Validate race requirements.
 */
export function validateRaceRequirements(
  race:
    | RaceDefinition
    | undefined,
  context:
    | RacePlayerContext
    | undefined,
  motor:
    | MotorInstance
    | undefined,
  driver:
    | DriverDefinition
    | undefined,
): RaceEntryValidation {
  const errors:
    RaceEntryErrorCode[] = [];

  const messages:
    string[] = [];

  const warnings:
    string[] = [];

  if (!race) {
    return {
      valid: false,

      errors: [
        "RACE_NOT_FOUND",
      ],

      messages: [
        "Event race tidak ditemukan.",
      ],

      warnings: [],
    };
  }

  if (!context) {
    return {
      valid: false,

      errors: [
        "INVALID_ENTRY",
      ],

      messages: [
        "Player context tidak tersedia.",
      ],

      warnings: [],
    };
  }

  if (!motor) {
    errors.push(
      "MOTOR_NOT_FOUND",
    );

    messages.push(
      "Motor tidak ditemukan.",
    );
  }

  if (!driver) {
    errors.push(
      "DRIVER_NOT_FOUND",
    );

    messages.push(
      "Driver tidak ditemukan.",
    );
  }

  if (motor) {
    const motorDefinition =
      getMotorDefinition(
        motor,
      );

    if (!motorDefinition) {
      errors.push(
        "MOTOR_NOT_FOUND",
      );

      messages.push(
        "Definisi motor tidak ditemukan.",
      );
    } else if (
      motorDefinition.class !==
      race.class
    ) {
      errors.push(
        "WRONG_MOTOR_CLASS",
      );

      messages.push(
        `Motor harus berada di kelas ${race.class}.`,
      );
    }

    const readiness =
      getMotorRaceReadiness(
        motor,
      );

    if (!readiness.ready) {
      errors.push(
        "MOTOR_NOT_READY",
      );

      messages.push(
        ...readiness.issues,
      );
    }

    if (
      motor.condition <
      20
    ) {
      errors.push(
        "MOTOR_CONDITION_TOO_LOW",
      );

      messages.push(
        "Condition motor terlalu rendah.",
      );
    }

    if (
      motor.condition <
      45
    ) {
      warnings.push(
        "Condition motor rendah dan meningkatkan mechanical risk.",
      );
    }
  }

  if (driver) {
    /**
     * Driver class compatibility.
     *
     * UNDER_125 can drive UNDER_110 and UNDER_125.
     * OPEN only accepts OPEN.
     */
    if (
      !isDriverClassEligible(
        driver.class,
        race.class,
      )
    ) {
      errors.push(
        "DRIVER_CLASS_NOT_ELIGIBLE",
      );

      messages.push(
        `Driver ${driver.class} tidak memenuhi kelas ${race.class}.`,
      );
    }
  }

  /* Explicit race requirements */
  for (
    const requirement of
      race.requirements
  ) {
    switch (
      requirement.type
    ) {
      case "GARAGE_LEVEL": {
        const required =
          Number(
            requirement.value,
          );

        if (
          context.garageLevel <
          required
        ) {
          errors.push(
            "GARAGE_LEVEL_TOO_LOW",
          );

          messages.push(
            `Garage minimal level ${required}.`,
          );
        }

        break;
      }

      case "REPUTATION": {
        const required =
          Number(
            requirement.value,
          );

        if (
          context.reputation <
          required
        ) {
          errors.push(
            "REPUTATION_TOO_LOW",
          );

          messages.push(
            `Reputation minimal ${required}.`,
          );
        }

        break;
      }

      case "DRIVER_CLASS": {
        if (
          driver &&
          !isDriverClassEligible(
            driver.class,
            String(
              requirement.value,
            ) as DriverClass,
          )
        ) {
          errors.push(
            "DRIVER_CLASS_NOT_ELIGIBLE",
          );

          messages.push(
            "Kelas driver tidak memenuhi requirement.",
          );
        }

        break;
      }

      case "DRIVER_LEVEL": {
        /**
         * RaceEntry intentionally does not require a level,
         * but callers may pass it in future.
         *
         * The catalog currently does not define DriverInstance.
         * Therefore a direct level requirement is rejected unless
         * caller extends this engine with richer player-driver state.
         */
        warnings.push(
          "Driver level requirement memerlukan driver instance dari GameState.",
        );

        break;
      }

      case "TEAM_LEVEL": {
        const required =
          Number(
            requirement.value,
          );

        if (
          (context.teamLevel ??
            0) <
          required
        ) {
          errors.push(
            "TEAM_LEVEL_TOO_LOW",
          );

          messages.push(
            `Team minimal level ${required}.`,
          );
        }

        break;
      }

      case "LICENSE": {
        const license =
          String(
            requirement.value,
          );

        if (
          !context.licenses?.includes(
            license,
          )
        ) {
          errors.push(
            "LICENSE_REQUIRED",
          );

          messages.push(
            `Lisensi ${license} diperlukan.`,
          );
        }

        break;
      }

      case "CHAMPIONSHIP": {
        const championshipId =
          String(
            requirement.value,
          );

        if (
          !context.championships?.includes(
            championshipId,
          )
        ) {
          /**
           * For championship races, the championship ID usually
           * means the player must have entered / unlocked the series.
           */
          warnings.push(
            `Progress championship ${championshipId} harus diverifikasi oleh GameState.`,
          );
        }

        break;
      }

      case "MOTOR_CLASS": {
        if (
          motor &&
          getMotorRaceClass(
            motor,
          ) !==
            String(
              requirement.value,
            )
        ) {
          errors.push(
            "WRONG_MOTOR_CLASS",
          );

          messages.push(
            "Kelas motor tidak memenuhi requirement.",
          );
        }

        break;
      }

      case "MOTOR_CATEGORY":
      case "MOTOR_CONDITION":
      case "DRIVER_LEVEL":
      case "MOTOR_CLASS":
      case "PART": {
        /**
         * These can require richer GameState data.
         * Core class / condition is checked where possible.
         */
        if (
          requirement.type ===
          "MOTOR_CONDITION"
        ) {
          const required =
            Number(
              requirement.value,
            );

          if (
            (motor?.condition ??
              0) <
            required
          ) {
            errors.push(
              "MOTOR_CONDITION_TOO_LOW",
            );

            messages.push(
              `Condition motor minimal ${required}%.`,
            );
          }
        }

        break;
      }
    }
  }

  return {
    valid:
      errors.length === 0,

    errors: unique(
      errors,
    ),

    messages:
      unique(
        messages,
      ),

    warnings:
      unique(
        warnings,
      ),
  };
}

/**
 * Driver class compatibility.
 */
export function isDriverClassEligible(
  driverClass:
    | DriverClass
    | string,
  raceClass:
    | RaceClass
    | string,
): boolean {
  if (
    raceClass ===
    "OPEN"
  ) {
    return (
      driverClass ===
      "OPEN"
    );
  }

  if (
    raceClass ===
      "UNDER_110" ||
    raceClass ===
      "UNDER_125"
  ) {
    return (
      driverClass ===
        "UNDER_125" ||
      driverClass ===
        "UNDER_110"
    );
  }

  if (
    raceClass ===
    "UNDER_150"
  ) {
    return (
      driverClass ===
        "UNDER_125" ||
      driverClass ===
        "UNDER_150" ||
      driverClass ===
        "OPEN"
    );
  }

  return false;
}

/**
 * Remove duplicate array values.
 */
export function unique<T>(
  items: readonly T[],
): T[] {
  return [
    ...new Set(
      items,
    ),
  ];
}

/* -------------------------------------------------------------------------- */
/* PERFORMANCE CALCULATION                                                    */
/* -------------------------------------------------------------------------- */

/**
 * Convert setup modifiers to safe values.
 */
export function normalizeSetupModifiers(
  modifiers:
    | RaceSetupModifiers
    | undefined,
): RaceSetupModifiers {
  return {
    launch:
      modifiers?.launch ?? 0,

    acceleration:
      modifiers?.acceleration ?? 0,

    topSpeed:
      modifiers?.topSpeed ?? 0,

    braking:
      modifiers?.braking ?? 0,

    handling:
      modifiers?.handling ?? 0,

    consistency:
      modifiers?.consistency ?? 0,

    reliability:
      modifiers?.reliability ?? 0,
  };
}

/**
 * Apply setup modifiers.
 */
export function applySetupModifiers(
  attributes: RacePerformance,
  modifiers:
    | RaceSetupModifiers
    | undefined,
): RacePerformance {
  const setup =
    normalizeSetupModifiers(
      modifiers,
    );

  return {
    ...attributes,

    launch:
      clampRaceStat(
        attributes.launch +
          (setup.launch ??
            0),
      ),

    acceleration:
      clampRaceStat(
        attributes.acceleration +
          (setup.acceleration ??
            0),
      ),

    topSpeed:
      clampRaceStat(
        attributes.topSpeed +
          (setup.topSpeed ??
            0),
      ),

    braking:
      clampRaceStat(
        attributes.braking +
          (setup.braking ??
            0),
      ),

    handling:
      clampRaceStat(
        attributes.handling +
          (setup.handling ??
            0),
      ),

    consistency:
      clampRaceStat(
        attributes.consistency +
          (setup.consistency ??
            0),
      ),

    reliability:
      clampRaceStat(
        attributes.reliability +
          (setup.reliability ??
            0),
      ),
  };
}

/**
 * Calculate base race performance.
 */
export function calculateRacePerformance(
  race:
    | RaceDefinition
    | undefined,
  motor:
    | MotorInstance
    | undefined,
  driver:
    | DriverDefinition
    | undefined,
  setupModifiers?:
    | RaceSetupModifiers,
  driverLevel = 1,
): RacePerformance {
  if (
    !race ||
    !motor ||
    !driver
  ) {
    return {
      launch: 0,
      acceleration: 0,
      topSpeed: 0,
      braking: 0,
      handling: 0,
      reaction: 0,
      consistency: 0,
      reliability: 0,
      overall: 0,
      weightedScore: 0,
      variance: 0,
      reliabilityPenalty: 0,
    };
  }

  const motorAttributes =
    getMotorRaceAttributes(
      motor,
    );

  const driverAttributes =
    getDriverRaceAttributes(
      driver,
    );

  const driverMultiplier =
    getDriverLevelMultiplier(
      driverLevel,
    );

  const raw: RacePerformance =
    {
      launch:
        combineStats(
          motorAttributes.launch,
          driverAttributes.launch,
          0.72,
          0.28,
          driverMultiplier,
        ),

      acceleration:
        motorAttributes.acceleration,

      topSpeed:
        motorAttributes.topSpeed,

      braking:
        combineStats(
          motorAttributes.braking,
          driverAttributes.control,
          0.78,
          0.22,
          driverMultiplier,
        ),

      handling:
        combineStats(
          motorAttributes.handling,
          driverAttributes.control,
          0.68,
          0.32,
          driverMultiplier,
        ),

      reaction:
        driverAttributes.reaction,

      consistency:
        driverAttributes.consistency,

      reliability:
        combineStats(
          motorAttributes.reliability,
          driverAttributes.focus,
          0.82,
          0.18,
          driverMultiplier,
        ),

      overall: 0,

      weightedScore: 0,

      variance: 0,

      reliabilityPenalty: 0,
    };

  const performance =
    applySetupModifiers(
      raw,
      setupModifiers,
    );

  const weightedScore =
    calculateRaceWeightedScore(
      race,
      performance,
    );

  const overall =
    Math.round(
      (
        performance.launch +
        performance.acceleration +
        performance.topSpeed +
        performance.braking +
        performance.handling +
        performance.reaction +
        performance.consistency +
        performance.reliability
      ) /
        8,
    );

  const reliabilityPenalty =
    calculateReliabilityPenalty(
      race,
      performance,
    );

  return {
    ...performance,

    overall,

    weightedScore,

    reliabilityPenalty,
  };
}

/**
 * Combine motor and driver contributions.
 */
export function combineStats(
  motorValue: number,
  driverValue: number,
  motorWeight: number,
  driverWeight: number,
  multiplier = 1,
): number {
  const result =
    (
      motorValue *
        motorWeight +
      driverValue *
        driverWeight
    ) *
    multiplier;

  return clampRaceStat(
    result,
  );
}

/**
 * Calculate weighted race score.
 */
export function calculateRaceWeightedScore(
  race:
    | RaceDefinition
    | undefined,
  performance:
    | RacePerformance
    | undefined,
): number {
  if (
    !race ||
    !performance
  ) {
    return 0;
  }

  const setup =
    race.setup;

  const weighted =
    performance.launch *
      setup.launchImportance +
    performance.acceleration *
      setup.accelerationImportance +
    performance.topSpeed *
      setup.topSpeedImportance +
    performance.braking *
      setup.brakingImportance +
    performance.handling *
      setup.handlingImportance +
    performance.reaction *
      setup.reactionImportance +
    performance.consistency *
      setup.consistencyImportance +
    performance.reliability *
      setup.reliabilityImportance;

  const weightTotal =
    setup.launchImportance +
    setup.accelerationImportance +
    setup.topSpeedImportance +
    setup.brakingImportance +
    setup.handlingImportance +
    setup.reactionImportance +
    setup.consistencyImportance +
    setup.reliabilityImportance;

  if (
    weightTotal <= 0
  ) {
    return 0;
  }

  return clampRaceStat(
    weighted /
      weightTotal,
  );
}

/**
 * Calculate reliability penalty.
 */
export function calculateReliabilityPenalty(
  race:
    | RaceDefinition
    | undefined,
  performance:
    | RacePerformance
    | undefined,
): number {
  if (
    !race ||
    !performance
  ) {
    return 0;
  }

  const pressure =
    race.conditions
      .reliabilityPressure;

  const reliability =
    performance.reliability;

  if (
    reliability >=
    pressure
  ) {
    return 0;
  }

  return clampRaceStat(
    (
      pressure -
      reliability
    ) *
      1.2,
  );
}

/**
 * Calculate mechanical risk percentage.
 */
export function calculateMechanicalRisk(
  race:
    | RaceDefinition
    | undefined,
  motor:
    | MotorInstance
    | undefined,
  performance?:
    | RacePerformance,
): number {
  if (
    !race ||
    !motor
  ) {
    return 100;
  }

  const stats =
    performance ??
    calculateRacePerformance(
      race,
      motor,
      undefined,
    );

  const reliability =
    calculateMotorRaceAttributes(
      motor,
    ).reliability;

  const conditionRisk =
    Math.max(
      0,
      (
        65 -
        motor.condition
      ) *
        0.65,
    );

  const pressureRisk =
    race.conditions
      .reliabilityPressure *
      0.8;

  const performanceRisk =
    Math.max(
      0,
      55 -
        stats.reliability,
    ) *
    0.55;

  const risk =
    conditionRisk +
    pressureRisk +
    performanceRisk;

  return clamp(
    Math.round(
      (
        risk +
        (
          100 -
          reliability
        ) *
          0.12
      ),
    ),
    0,
    100,
  );
}

/* -------------------------------------------------------------------------- */
/* RACE TIME                                                                  */
/* -------------------------------------------------------------------------- */

/**
 * Calculate nominal time from distance.
 */
export function calculateBaseRaceTimeMs(
  race:
    | RaceDefinition
    | undefined,
): number {
  if (!race) {
    return 0;
  }

  const bucket =
    getRaceDistanceBucket(
      race.distance.meters,
    );

  const base =
    BASE_TIME_MS_BY_DISTANCE[
      bucket
    ];

  /**
   * Scale base time with actual distance.
   *
   * This avoids 201m and 1,201m having similar times.
   */
  const distanceRatio =
    Math.sqrt(
      race.distance.meters /
        (
          bucket === "SHORT"
            ? 201
            : bucket ===
                "MEDIUM"
              ? 402
              : 1_201
        ),
    );

  return Math.round(
    base *
      distanceRatio,
  );
}

/**
 * Convert race score into final time.
 */
export function calculateFinishTimeMs(
  race:
    | RaceDefinition
    | undefined,
  performance:
    | RacePerformance
    | undefined,
  random: RandomFn,
  difficultyMultiplier = 1,
): number {
  if (
    !race ||
    !performance
  ) {
    return MAX_FINISH_TIME_MS;
  }

  const baseTime =
    calculateBaseRaceTimeMs(
      race,
    );

  /**
   * A higher performance score means faster time.
   *
   * Score 0   => slow
   * Score 50  => neutral
   * Score 100 => fast
   */
  const normalized =
    clamp(
      performance.weightedScore,
      0,
      100,
    ) /
    100;

  const performanceFactor =
    1 -
    (
      normalized -
      0.5
    ) *
      PERFORMANCE_TIME_FACTOR;

  const variance =
    (
      safeRandom(random) *
        2 -
      1
    ) *
    MAX_VARIANCE_PERCENT;

  let result =
    baseTime *
    performanceFactor *
    (
      1 +
      variance
    );

  /**
   * Reliability failure adds time before DNF is decided.
   */
  if (
    performance.reliabilityPenalty >
    0
  ) {
    result *=
      1 +
      performance.reliabilityPenalty /
        450;
  }

  result *=
    Math.max(
      0.8,
      Math.min(
        1.3,
        difficultyMultiplier,
      ),
    );

  return Math.round(
    clamp(
      result,
      MIN_FINISH_TIME_MS,
      MAX_FINISH_TIME_MS,
    ),
  );
}

/* -------------------------------------------------------------------------- */
/* DNF / MECHANICAL FAILURE                                                   */
/* -------------------------------------------------------------------------- */

/**
 * Calculate chance of DNF.
 *
 * Result is 0-1.
 */
export function calculateDnfChance(
  race:
    | RaceDefinition
    | undefined,
  motor:
    | MotorInstance
    | undefined,
  performance:
    | RacePerformance
    | undefined,
  mechanicalRisk?: number,
): number {
  if (
    !race ||
    !motor
  ) {
    return 1;
  }

  const risk =
    mechanicalRisk ??
    calculateMechanicalRisk(
      race,
      motor,
      performance,
    );

  /**
   * Baseline:
   * - healthy motor, low-pressure event -> ~1%
   * - high risk -> substantially higher
   */
  let chance =
    DNF_BASE_CHANCE +
    risk / 450;

  if (
    race.conditions
      .reliabilityPressure >=
    20
  ) {
    chance += 0.04;
  }

  if (
    motor.condition <
    40
  ) {
    chance += 0.06;
  }

  if (
    performance &&
    performance.reliability <
    40
  ) {
    chance += 0.05;
  }

  return clamp(
    chance,
    0,
    0.85,
  );
}

/**
 * Pick DNF reason.
 */
export function getDnfReason(
  race:
    | RaceDefinition
    | undefined,
  performance:
    | RacePerformance
    | undefined,
  motor:
    | MotorInstance
    | undefined,
  random: RandomFn,
): RaceDnfReason {
  if (!race) {
    return "NO_FINISH";
  }

  const reliability =
    performance?.reliability ??
    0;

  const condition =
    motor?.condition ??
    0;

  const roll =
    safeRandom(
      random,
    );

  if (
    condition <
    20
  ) {
    return "ENGINE_FAILURE";
  }

  if (
    race.conditions
      .reliabilityPressure >=
      22 &&
    reliability <
    45
  ) {
    return "MECHANICAL_FAILURE";
  }

  if (
    roll <
    0.25
  ) {
    return "CRASH";
  }

  return "MECHANICAL_FAILURE";
}

/* -------------------------------------------------------------------------- */
/* WEAR                                                                      */
/* -------------------------------------------------------------------------- */

/**
 * Calculate motor wear after race.
 */
export function calculateMotorRaceWear(
  race:
    | RaceDefinition
    | undefined,
  motor:
    | MotorInstance
    | undefined,
  performance:
    | RacePerformance
    | undefined,
  dnf = false,
): number {
  if (
    !race ||
    !motor
  ) {
    return 0;
  }

  const pressure =
    race.conditions
      .reliabilityPressure;

  const reliability =
    performance?.reliability ??
    getMotorRaceAttributes(
      motor,
    ).reliability;

  const distanceFactor =
    Math.sqrt(
      race.distance.meters /
        201,
    );

  const reliabilityFactor =
    Math.max(
      0.5,
      1 +
        (
          60 -
          reliability
        ) /
          100,
    );

  const conditionFactor =
    motor.condition <
    50
      ? 1.25
      : 1;

  const dnfFactor =
    dnf
      ? 1.75
      : 1;

  const wear =
    MOTOR_WEAR_BASE *
    distanceFactor *
    (
      1 +
      pressure /
        100
    ) *
    reliabilityFactor *
    conditionFactor *
    dnfFactor;

  return Number(
    wear.toFixed(2),
  );
}

/**
 * Calculate installed-part wear.
 *
 * Keys match motor.ts installedParts categories.
 */
export function calculateInstalledPartWear(
  motor:
    | MotorInstance
    | undefined,
  race:
    | RaceDefinition
    | undefined,
  performance:
    | RacePerformance
    | undefined,
  dnf = false,
): Record<string, number> {
  if (
    !motor ||
    !race
  ) {
    return {};
  }

  const result:
    Record<string, number> =
      {};

  const base =
    calculateMotorRaceWear(
      race,
      motor,
      performance,
      dnf,
    );

  for (
    const category of Object.keys(
      motor.installedParts,
    )
  ) {
    if (
      !motor.installedParts[
        category
      ]
    ) {
      continue;
    }

    /**
     * Brakes / tires / clutch / drivetrain receive
     * more wear in race use.
     */
    let multiplier = 0.55;

    if (
      category ===
      "BRAKE"
    ) {
      multiplier = 0.85;
    } else if (
      category ===
      "TIRE"
    ) {
      multiplier = 0.95;
    } else if (
      category ===
      "CLUTCH"
    ) {
      multiplier = 0.9;
    } else if (
      category ===
      "TRANSMISSION"
    ) {
      multiplier = 0.75;
    } else if (
      category ===
      "ENGINE"
    ) {
      multiplier = 1;
    } else if (
      category ===
      "EXHAUST"
    ) {
      multiplier = 0.5;
    }

    if (
      dnf
    ) {
      multiplier *= 1.35;
    }

    result[
      category
    ] = Number(
      (
        base *
        multiplier *
        (
          PART_WEAR_BASE /
          MOTOR_WEAR_BASE
        )
      ).toFixed(2),
    );
  }

  return result;
}

/* -------------------------------------------------------------------------- */
/* REWARD CALCULATION                                                         */
/* -------------------------------------------------------------------------- */

/**
 * Get prize rewards from race definition.
 */
export function getPositionRewards(
  race:
    | RaceDefinition
    | undefined,
  position: number,
): RaceResultReward[] {
  if (
    !race ||
    position <= 0
  ) {
    return [];
  }

  const prize =
    race.prizes.find(
      (entry) =>
        entry.position ===
        position,
    );

  if (!prize) {
    return [];
  }

  return prize.rewards.map(
    (reward) => ({
      type:
        reward.type,
      amount:
        reward.amount,
    }),
  );
}

/**
 * Get direct race rewards.
 */
export function getDirectRaceRewards(
  race:
    | RaceDefinition
    | undefined,
): RaceResultReward[] {
  if (!race) {
    return [];
  }

  return race.rewards.map(
    (reward) => ({
      type:
        reward.type,
      amount:
        reward.amount,
    }),
  );
}

/**
 * Get all rewards earned by position.
 */
export function calculateRaceRewards(
  race:
    | RaceDefinition
    | undefined,
  position: number,
): RaceResultReward[] {
  if (!race) {
    return [];
  }

  return [
    ...getDirectRaceRewards(
      race,
    ),

    ...getPositionRewards(
      race,
      position,
    ),
  ];
}

/**
 * Calculate championship points.
 */
export function calculateChampionshipPoints(
  race:
    | RaceDefinition
    | undefined,
  position: number,
): number {
  if (
    !race ||
    !race.championship
  ) {
    return 0;
  }

  const reward =
    getPositionRewards(
      race,
      position,
    ).find(
      (entry) =>
        entry.type ===
        "CHAMPIONSHIP_POINTS",
    );

  return (
    reward?.amount ??
    0
  );
}

/* -------------------------------------------------------------------------- */
/* OPPONENT GENERATION                                                        */
/* -------------------------------------------------------------------------- */

/**
 * Generate abstract opponents from static catalogs.
 *
 * This is deliberately independent from player ownership.
 */
export function generateDefaultOpponents(
  race:
    | RaceDefinition
    | undefined,
  count: number,
  random: RandomFn,
): RaceOpponentDefinition[] {
  if (!race) {
    return [];
  }

  const drivers =
    getAvailableDriversForRace(
      race,
    );

  const motors =
    getAvailableMotorDefinitionsForRace(
      race,
    );

  if (
    drivers.length ===
      0 ||
    motors.length ===
      0
  ) {
    return [];
  }

  const result:
    RaceOpponentDefinition[] =
      [];

  const used =
    new Set<string>();

  const safeCount =
    Math.max(
      0,
      Math.floor(
        count,
      ),
    );

  for (
    let i = 0;
    i < safeCount;
    i += 1
  ) {
    let driver =
      randomItem(
        drivers,
        random,
      );

    let motor =
      randomItem(
        motors,
        random,
      );

    /**
     * Try to avoid the exact same driver + motor pairing.
     */
    let attempts = 0;

    while (
      driver &&
      motor &&
      used.has(
        `${driver.id}:${motor.id}`,
      ) &&
      attempts < 10
    ) {
      driver =
        randomItem(
          drivers,
          random,
        );

      motor =
        randomItem(
          motors,
          random,
        );

      attempts += 1;
    }

    if (
      !driver ||
      !motor
    ) {
      break;
    }

    const key =
      `${driver.id}:${motor.id}`;

    used.add(key);

    result.push({
      driverId:
        driver.id,

      motorDefinitionId:
        motor.id,

      motorCondition:
        generateOpponentCondition(
          random,
        ),

      driverLevel:
        generateOpponentDriverLevel(
          race,
          random,
        ),

      setupModifiers:
        generateOpponentSetup(
          race,
          random,
        ),
    });
  }

  return result;
}

/**
 * Return drivers eligible for race.
 */
export function getAvailableDriversForRace(
  race:
    | RaceDefinition
    | undefined,
): DriverDefinition[] {
  if (!race) {
    return [];
  }

  /**
   * Driver catalog helper isn't assumed to know RaceClass
   * directly, so use static catalog access.
   */
  const module =
    requireDriversModule();

  return module.filter(
    (
      driver,
    ) =>
      isDriverClassEligible(
        driver.class,
        race.class,
      ),
  );
}

/**
 * Return motor definitions eligible for race.
 */
export function getAvailableMotorDefinitionsForRace(
  race:
    | RaceDefinition
    | undefined,
): ReturnType<
  typeof import("../data/motors")
    .getMotorsByClass
> {
  if (!race) {
    return [];
  }

  const module =
    requireMotorsModule();

  return module.filter(
    (motor) =>
      motor.class ===
      race.class,
  );
}

/**
 * The dynamic imports above are avoided in actual execution by
 * these synchronous module access helpers.
 *
 * Keeping the implementation centralized means changing the data
 * module does not spread across race logic.
 */
function requireDriversModule(): DriverDefinition[] {
  /**
   * This function is replaced below by the direct static import
   * reference exposed through the module-local bridge.
   */
  return DRIVER_CATALOG;
}

function requireMotorsModule() {
  return MOTOR_CATALOG;
}

/* -------------------------------------------------------------------------- */
/* DIRECT CATALOG BRIDGE                                                      */
/* -------------------------------------------------------------------------- */

/**
 * Static imports used by opponent generation.
 *
 * They are separated here to keep the top import section focused
 * on the primary race engine dependencies.
 */

import {
  getDrivers,
} from "../data/drivers";

import {
  getMotors,
  type MotorDefinition,
} from "../data/motors";

const DRIVER_CATALOG =
  getDrivers();

const MOTOR_CATALOG =
  getMotors();

/**
 * The imported MotorDefinition is intentionally used here too.
 */
void (0 as unknown as MotorDefinition);

/* -------------------------------------------------------------------------- */
/* OPPONENT BALANCING                                                         */
/* -------------------------------------------------------------------------- */

/**
 * Generate opponent motor condition.
 */
export function generateOpponentCondition(
  random: RandomFn,
): number {
  const roll =
    safeRandom(random);

  /**
   * Most opponents should be in usable condition.
   */
  if (
    roll < 0.1
  ) {
    return 55 +
      Math.round(
        safeRandom(
          random,
        ) * 15,
      );
  }

  return 72 +
    Math.round(
      safeRandom(
        random,
      ) * 26,
    );
}

/**
 * Generate opponent driver level based on event.
 */
export function generateOpponentDriverLevel(
  race:
    | RaceDefinition
    | undefined,
  random: RandomFn,
): number {
  if (!race) {
    return 1;
  }

  let base = 1;

  switch (
    race.difficulty
  ) {
    case "BEGINNER":
      base = 1;
      break;

    case "NOVICE":
      base = 2;
      break;

    case "INTERMEDIATE":
      base = 3;
      break;

    case "HARD":
      base = 4;
      break;

    case "PRO":
      base = 5;
      break;

    case "ELITE":
      base = 7;
      break;
  }

  const variance =
    Math.floor(
      safeRandom(
        random,
      ) * 3,
    ) - 1;

  return Math.max(
    1,
    base + variance,
  );
}

/**
 * Generate opponent setup variation.
 */
export function generateOpponentSetup(
  race:
    | RaceDefinition
    | undefined,
  random: RandomFn,
): RaceSetupModifiers {
  if (!race) {
    return {};
  }

  const variation =
    () =>
      Math.round(
        (
          safeRandom(
            random,
          ) *
            2 -
          1
        ) *
          5,
      );

  return {
    launch:
      variation(),

    acceleration:
      variation(),

    topSpeed:
      variation(),

    braking:
      variation(),

    handling:
      variation(),

    consistency:
      variation(),

    reliability:
      variation(),
  };
}

/* -------------------------------------------------------------------------- */
/* FIELD SIMULATION                                                           */
/* -------------------------------------------------------------------------- */

/**
 * Build player's simulated field entry.
 */
export function createPlayerSimulationDriver(
  race:
    | RaceDefinition
    | undefined,
  entry:
    | RaceEntry
    | undefined,
  random: RandomFn,
): RaceSimulationDriver | undefined {
  if (
    !race ||
    !entry
  ) {
    return undefined;
  }

  const driver =
    getDriverById(
      entry.driverId,
    );

  if (!driver) {
    return undefined;
  }

  const performance =
    calculateRacePerformance(
      race,
      entry.motor,
      driver,
      entry.setupModifiers,
    );

  const finalPerformance =
    applyRaceVariance(
      performance,
      random,
    );

  return {
    id:
      `PLAYER-${entry.motor.id}`,

    name:
      getRaceDriverName(
        driver,
      ),

    motorClass:
      getMotorRaceClass(
        entry.motor,
      ) ?? race.class,

    driverClass:
      driver.class,

    motor:
      entry.motor,

    basePerformance:
      performance,

    finalPerformance,

    finishTimeMs:
      0,

    position:
      0,

    dnf:
      false,
  };
}

/**
 * Build opponent simulated driver.
 */
export function createOpponentSimulationDriver(
  race:
    | RaceDefinition
    | undefined,
  opponent:
    | RaceOpponentDefinition
    | undefined,
  random: RandomFn,
): RaceSimulationDriver
  | undefined {
  if (
    !race ||
    !opponent
  ) {
    return undefined;
  }

  const driver =
    getDriverById(
      opponent.driverId,
    );

  const motorDefinition =
    getMotorDefinitionById(
      opponent.motorDefinitionId,
    );

  if (
    !driver ||
    !motorDefinition
  ) {
    return undefined;
  }

  const condition =
    clampRaceStat(
      opponent.motorCondition ??
        generateOpponentCondition(
          random,
        ),
    );

  const motor =
    createSimulationMotor(
      motorDefinition.id,
      condition,
    );

  if (!motor) {
    return undefined;
  }

  const performance =
    calculateRacePerformance(
      race,
      motor,
      driver,
      opponent.setupModifiers,
      opponent.driverLevel ?? 1,
    );

  const finalPerformance =
    applyRaceVariance(
      performance,
      random,
    );

  return {
    id:
      `${driver.id}-${motor.id}`,

    name:
      getRaceDriverName(
        driver,
      ),

    motorClass:
      motorDefinition.class,

    driverClass:
      driver.class,

    motor,

    basePerformance:
      performance,

    finalPerformance,

    finishTimeMs:
      0,

    position:
      0,

    dnf:
      false,
  };
}

/**
 * Get motor definition without exposing another game-state layer.
 */
export function getMotorDefinitionById(
  id: string,
) {
  return MOTOR_CATALOG.find(
    (motor) =>
      motor.id === id,
  );
}

/**
 * Create temporary motor instance for opponent simulation.
 */
export function createSimulationMotor(
  definitionId: string,
  condition: number,
): MotorInstance | undefined {
  const definition =
    getMotorDefinitionById(
      definitionId,
    );

  if (!definition) {
    return undefined;
  }

  return {
    id:
      `OPP-${definitionId}`,

    definitionId,

    condition:
      clampRaceStat(
        condition,
      ),

    installedParts:
      {},

    mileage:
      0,

    raceCount:
      0,

    serviceCount:
      0,

    acquiredAt:
      0,

    status:
      "READY",
  };
}

/**
 * Apply controlled random variance.
 *
 * More consistent drivers receive slightly lower variance.
 */
export function applyRaceVariance(
  performance:
    | RacePerformance
    | undefined,
  random: RandomFn,
): RacePerformance {
  if (!performance) {
    return {
      launch: 0,
      acceleration: 0,
      topSpeed: 0,
      braking: 0,
      handling: 0,
      reaction: 0,
      consistency: 0,
      reliability: 0,
      overall: 0,
      weightedScore: 0,
      variance: 0,
      reliabilityPenalty: 0,
    };
  }

  const consistencyFactor =
    performance.consistency /
    100;

  const maxVariance =
    1 +
    (
      1 -
      consistencyFactor
    ) *
      3;

  const delta =
    (
      safeRandom(random) *
        2 -
      1
    ) *
    maxVariance;

  const final: RacePerformance =
    {
      ...performance,

      launch:
        clampRaceStat(
          performance.launch +
            delta,
        ),

      acceleration:
        clampRaceStat(
          performance.acceleration +
            delta,
        ),

      topSpeed:
        clampRaceStat(
          performance.topSpeed +
            delta,
        ),

      braking:
        clampRaceStat(
          performance.braking +
            delta,
        ),

      handling:
        clampRaceStat(
          performance.handling +
            delta,
        ),

      reaction:
        clampRaceStat(
          performance.reaction +
            delta,
        ),

      consistency:
        clampRaceStat(
          performance.consistency +
            delta *
              0.5,
        ),

      reliability:
        clampRaceStat(
          performance.reliability +
            delta *
              0.4,
        ),

      variance:
        delta,
    };

  /**
   * weightedScore must be recomputed by the race system
   * after variance is applied. It cannot use the original race
   * weights here because the race definition is not passed into
   * this helper.
   *
   * Race simulation recalculates it below.
   */
  return final;
}

/**
 * Recompute final weighted score.
 */
export function recomputeWeightedPerformance(
  race:
    | RaceDefinition
    | undefined,
  performance:
    | RacePerformance
    | undefined,
): RacePerformance {
  if (
    !race ||
    !performance
  ) {
    return {
      launch: 0,
      acceleration: 0,
      topSpeed: 0,
      braking: 0,
      handling: 0,
      reaction: 0,
      consistency: 0,
      reliability: 0,
      overall: 0,
      weightedScore: 0,
      variance: 0,
      reliabilityPenalty: 0,
    };
  }

  const weightedScore =
    calculateRaceWeightedScore(
      race,
      performance,
    );

  const overall =
    Math.round(
      (
        performance.launch +
        performance.acceleration +
        performance.topSpeed +
        performance.braking +
        performance.handling +
        performance.reaction +
        performance.consistency +
        performance.reliability
      ) /
        8,
    );

  const reliabilityPenalty =
    calculateReliabilityPenalty(
      race,
      performance,
    );

  return {
    ...performance,

    weightedScore,

    overall,

    reliabilityPenalty,
  };
}

/* -------------------------------------------------------------------------- */
/* COMPLETE RACE SIMULATION                                                   */
/* -------------------------------------------------------------------------- */

/**
 * Simulate a complete race.
 */
export function simulateRace(
  entry:
    | RaceEntry
    | undefined,
  context:
    | RacePlayerContext
    | undefined,
  options: RaceSimulationOptions = {},
): RaceResult | undefined {
  if (
    !entry ||
    !context
  ) {
    return undefined;
  }

  const race =
    getRaceById(
      entry.raceId,
    );

  if (!race) {
    return undefined;
  }

  const driver =
    getDriverById(
      entry.driverId,
    );

  if (!driver) {
    return undefined;
  }

  const validation =
    validateRaceRequirements(
      race,
      context,
      entry.motor,
      driver,
    );

  if (
    !validation.valid
  ) {
    return undefined;
  }

  const random =
    options.random ??
    (
      options.seed !==
      undefined
        ? createSeededRandom(
            options.seed,
          )
        : Math.random
    );

  const difficultyMultiplier =
    options.difficultyMultiplier ??
    1;

  const playerDriver =
    createPlayerSimulationDriver(
      race,
      {
        ...entry,

        setupModifiers:
          options.playerSetupModifiers ??
          entry.setupModifiers,
      },
      random,
    );

  if (
    !playerDriver
  ) {
    return undefined;
  }

  playerDriver.finalPerformance =
    recomputeWeightedPerformance(
      race,
      playerDriver.finalPerformance,
    );

  const mechanicalRisk =
    calculateMechanicalRisk(
      race,
      entry.motor,
      playerDriver.finalPerformance,
    );

  const playerDnfChance =
    calculateDnfChance(
      race,
      entry.motor,
      playerDriver.finalPerformance,
      mechanicalRisk,
    );

  if (
    safeRandom(
      random,
    ) <
    playerDnfChance
  ) {
    playerDriver.dnf =
      true;

    playerDriver.dnfReason =
      getDnfReason(
        race,
        playerDriver.finalPerformance,
        entry.motor,
        random,
      );

    playerDriver.finishTimeMs =
      MAX_FINISH_TIME_MS;
  } else {
    playerDriver.finishTimeMs =
      calculateFinishTimeMs(
        race,
        playerDriver.finalPerformance,
        random,
        difficultyMultiplier,
      );
  }

  const opponentDefinitions =
    options.opponents ??
    generateDefaultOpponents(
      race,
      getRequestedOpponentCount(
        race,
        options.opponentCount,
      ),
      random,
    );

  const opponents:
    RaceSimulationDriver[] =
      [];

  for (
    const opponent of
      opponentDefinitions
  ) {
    const simulated =
      createOpponentSimulationDriver(
        race,
        opponent,
        random,
      );

    if (!simulated) {
      continue;
    }

    simulated.finalPerformance =
      recomputeWeightedPerformance(
        race,
        simulated.finalPerformance,
      );

    const opponentMotor =
      simulated.motor;

    const opponentRisk =
      calculateMechanicalRisk(
        race,
        opponentMotor,
        simulated.finalPerformance,
      );

    const opponentDnfChance =
      calculateDnfChance(
        race,
        opponentMotor,
        simulated.finalPerformance,
        opponentRisk,
      );

    if (
      safeRandom(
        random,
      ) <
      opponentDnfChance
    ) {
      simulated.dnf =
        true;

      simulated.dnfReason =
        getDnfReason(
          race,
          simulated.finalPerformance,
          opponentMotor,
          random,
        );

      simulated.finishTimeMs =
        MAX_FINISH_TIME_MS;
    } else {
      simulated.finishTimeMs =
        calculateFinishTimeMs(
          race,
          simulated.finalPerformance,
          random,
          difficultyMultiplier,
        );
    }

    opponents.push(
      simulated,
    );
  }

  const field = [
    playerDriver,
    ...opponents,
  ];

  assignRacePositions(
    field,
  );

  /**
   * If we accidentally generated fewer opponents than minimum field,
   * the simulation still remains valid. Field is never fabricated
   * after the fact.
   */
  const playerPosition =
    playerDriver.position;

  const playerFinished =
    !playerDriver.dnf;

  const rewards =
    playerFinished
      ? calculateRaceRewards(
          race,
          playerPosition,
        )
      : calculateDidNotFinishRewards(
          race,
        );

  const motorWear =
    calculateMotorRaceWear(
      race,
      entry.motor,
      playerDriver.finalPerformance,
      playerDriver.dnf,
    );

  const partWear =
    calculateInstalledPartWear(
      entry.motor,
      race,
      playerDriver.finalPerformance,
      playerDriver.dnf,
    );

  const championshipPoints =
    playerFinished
      ? calculateChampionshipPoints(
          race,
          playerPosition,
        )
      : 0;

  return {
    raceId:
      race.id,

    simulatedAt:
      Date.now(),

    playerPosition,

    playerFinished,

    playerFinishTimeMs:
      playerDriver.finishTimeMs,

    playerFinishTime:
      playerDriver.dnf
        ? "DNF"
        : formatRaceTime(
            playerDriver.finishTimeMs,
          ),

    fieldSize:
      field.length,

    standings:
      field,

    rewards,

    motorWear,

    partWear,

    championshipPoints,

    performanceScore:
      playerDriver.finalPerformance
        .weightedScore,

    mechanicalRisk,

    seed:
      options.seed,
  };
}

/**
 * Determine opponent count.
 */
export function getRequestedOpponentCount(
  race:
    | RaceDefinition
    | undefined,
  requested?: number,
): number {
  if (!race) {
    return 0;
  }

  if (
    requested !==
    undefined
  ) {
    return clamp(
      Math.floor(
        requested,
      ),
      1,
      race.field.maximumDrivers -
        1,
    );
  }

  return clamp(
    DEFAULT_OPPONENT_COUNT,
    race.field.minimumDrivers -
      1,
    race.field.maximumDrivers -
      1,
  );
}

/**
 * Assign positions by finish time.
 *
 * DNF always ranks behind finishers.
 */
export function assignRacePositions(
  field:
    | RaceSimulationDriver[]
    | undefined,
): void {
  if (!field) {
    return;
  }

  field.sort(
    (
      a,
      b,
    ) => {
      if (
        a.dnf &&
        !b.dnf
      ) {
        return 1;
      }

      if (
        !a.dnf &&
        b.dnf
      ) {
        return -1;
      }

      return (
        a.finishTimeMs -
        b.finishTimeMs
      );
    },
  );

  for (
    let i = 0;
    i < field.length;
    i += 1
  ) {
    field[i].position =
      i + 1;
  }
}

/**
 * Rewards for DNF.
 *
 * Direct event participation rewards are still granted,
 * but no finishing prize or championship points.
 */
export function calculateDidNotFinishRewards(
  race:
    | RaceDefinition
    | undefined,
): RaceResultReward[] {
  if (!race) {
    return [];
  }

  return race.rewards.filter(
    (reward) =>
      reward.type !==
      "CHAMPIONSHIP_POINTS",
  ).map(
    (reward) => ({
      type:
        reward.type,
      amount:
        reward.amount,
    }),
  );
}

/* -------------------------------------------------------------------------- */
/* RACE SCORE HELPERS                                                         */
/* -------------------------------------------------------------------------- */

/**
 * Calculate a simplified race score for UI preview.
 *
 * This does not use RNG.
 */
export function calculateRacePreviewScore(
  race:
    | RaceDefinition
    | undefined,
  motor:
    | MotorInstance
    | undefined,
  driver:
    | DriverDefinition
    | undefined,
  setupModifiers?:
    | RaceSetupModifiers,
): number {
  const performance =
    calculateRacePerformance(
      race,
      motor,
      driver,
      setupModifiers,
    );

  return performance.weightedScore;
}

/**
 * Calculate launch advantage.
 */
export function calculateLaunchAdvantage(
  race:
    | RaceDefinition
    | undefined,
  motor:
    | MotorInstance
    | undefined,
  driver:
    | DriverDefinition
    | undefined,
): number {
  if (
    !race ||
    !motor ||
    !driver
  ) {
    return 0;
  }

  const performance =
    calculateRacePerformance(
      race,
      motor,
      driver,
    );

  return clampRaceStat(
    (
      performance.launch *
        race.setup.launchImportance +
      performance.reaction *
        race.setup.reactionImportance
    ) /
      Math.max(
        1,
        race.setup.launchImportance +
          race.setup.reactionImportance,
      ),
  );
}

/**
 * Calculate consistency advantage.
 */
export function calculateConsistencyAdvantage(
  race:
    | RaceDefinition
    | undefined,
  motor:
    | MotorInstance
    | undefined,
  driver:
    | DriverDefinition
    | undefined,
): number {
  if (
    !race ||
    !motor ||
    !driver
  ) {
    return 0;
  }

  const performance =
    calculateRacePerformance(
      race,
      motor,
      driver,
    );

  return clampRaceStat(
    (
      performance.consistency *
        race.setup.consistencyImportance +
      performance.reliability *
        race.setup.reliabilityImportance
    ) /
      Math.max(
        1,
        race.setup.consistencyImportance +
          race.setup.reliabilityImportance,
      ),
  );
}

/**
 * Return primary race factor.
 */
export function getRacePrimaryFactor(
  race:
    | RaceDefinition
    | undefined,
): {
  factor:
    | "launch"
    | "acceleration"
    | "topSpeed"
    | "braking"
    | "handling"
    | "reaction"
    | "consistency"
    | "reliability";

  weight: number;
} {
  if (!race) {
    return {
      factor:
        "consistency",

      weight: 0,
    };
  }

  const candidates = [
    [
      "launch",
      race.setup.launchImportance,
    ],

    [
      "acceleration",
      race.setup.accelerationImportance,
    ],

    [
      "topSpeed",
      race.setup.topSpeedImportance,
    ],

    [
      "braking",
      race.setup.brakingImportance,
    ],

    [
      "handling",
      race.setup.handlingImportance,
    ],

    [
      "reaction",
      race.setup.reactionImportance,
    ],

    [
      "consistency",
      race.setup.consistencyImportance,
    ],

    [
      "reliability",
      race.setup.reliabilityImportance,
    ],
  ] as const;

  return candidates.reduce(
    (
      best,
      current,
    ) =>
      current[1] >
      best[1]
        ? current
        : best,
  );
}

/**
 * Return whether a race has meaningful mechanical risk.
 */
export function isHighRiskRace(
  race:
    | RaceDefinition
    | undefined,
): boolean {
  if (!race) {
    return false;
  }

  return (
    race.conditions
      .reliabilityPressure >=
    HIGH_RISK_THRESHOLD / 3
  );
}

/* -------------------------------------------------------------------------- */
/* VALIDATION                                                                 */
/* -------------------------------------------------------------------------- */

/**
 * Validate a race result.
 *
 * Useful before persisting it in GameState.
 */
export function validateRaceResult(
  result:
    | RaceResult
    | undefined,
): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];

  if (!result) {
    return {
      valid: false,
      errors: [
        "Race result tidak tersedia.",
      ],
    };
  }

  if (
    !result.raceId
  ) {
    errors.push(
      "raceId kosong.",
    );
  }

  if (
    result.fieldSize <= 0
  ) {
    errors.push(
      "fieldSize harus lebih besar dari 0.",
    );
  }

  if (
    result.playerPosition <=
      0 ||
    result.playerPosition >
      result.fieldSize
  ) {
    errors.push(
      "playerPosition tidak valid.",
    );
  }

  if (
    result.playerFinished &&
    result.playerFinishTimeMs <=
      0
  ) {
    errors.push(
      "Finished player harus memiliki finish time.",
    );
  }

  if (
    result.motorWear < 0
  ) {
    errors.push(
      "motorWear tidak boleh negatif.",
    );
  }

  if (
    result.championshipPoints < 0
  ) {
    errors.push(
      "championshipPoints tidak boleh negatif.",
    );
  }

  const positions =
    result.standings.map(
      (entry) =>
        entry.position,
    );

  const uniquePositions =
    unique(
      positions,
    );

  if (
    uniquePositions.length !==
    positions.length
  ) {
    errors.push(
      "Standings memiliki posisi duplikat.",
    );
  }

  if (
    result.standings.length !==
    result.fieldSize
  ) {
    errors.push(
      "Jumlah standings tidak sama dengan fieldSize.",
    );
  }

  return {
    valid:
      errors.length === 0,

    errors,
  };
}
